### ISSUE TITLE
Match candidate transcripts to gene(s)

### ISSUE THREAD

**Issue by dewyman** [mortazavilab/TALON#2]
### High-level
If the candidate transcript overlaps with an annotated gene, then we consider it a transcript of that gene. We could potentially allow more than one match at first and then select the one that is "better". In addition, we may want to think about how much overlap should count.

### Details: How will I assign transcripts to genes in practice?
One option would be to use Bedtools intersect. This would be similar in spirit to TranscriptClean. Other ideas might include taking advantage of sorting. I did a brief Google search for "data structures for comparing numeric intervals", and the results suggest to me that there might be good ways of doing this that would not require an outside tool. For instance, there is a data structure called an interval tree that seems appropriate. This would be applicable to other areas of the program as well.
https://en.wikipedia.org/wiki/Interval_tree
This Python library seems like a useful implementation because you can store any object linked to a given interval, for instance, a hypothetical gene class object. And we can safely assume that two genes never have the exact same coordinates.
https://pypi.python.org/pypi/intervaltree

Additional considerations: 
* Chromosomes need to be handled separately (can't just have one position interval tree)
    * Solution: Use a dict: Each chromosome key points to its own interval tree
* Strand
    * I'm going to ignore this for the moment, but it may need to be its own issue

I decided it would be worthwhile to create a dedicated GeneTree class to manage the dict of interval trees, and create dedicated methods for it in order to keep the code readable. I have now implemented this class.

### Tasks
- [x] Write the GeneTree class
- [x] Write a GeneTree class function: given an interval, get the genes that overlap with it
- [x] Write the Gene class
- [x] Deal with the strand issue
