### ISSUE TITLE
Process SAM file of transcripts

### ISSUE THREAD

**Issue by dewyman** [mortazavilab/TALON#3]
I will need to read in transcripts from SAM files and create representations of them that allow for comparisons against the annotation.

I think it would make sense for the transcripts to belong to the same class as the annotation-derived transcripts. Or at least be a subclass of them.

### Tasks
- [x] Superficial SAM reading code that opens the file and goes line by line
- [x] Write and test a function that computes the end position of the transcript
- [x] Code to get introns from transcript (straight from jI field, or compute them if missing)
- [x] Code to get exon structure of a transcript. Similar to TranscriptClean.
- [x] Decide how we are going to treat multi-mapping transcripts. I could imagine a version of this where we allow multi-mapping by effectively doing several interval searches against the genes. Then, the gene lists could be combined and processed just like any other gene overlaps would be (i.e. trying to find the best overlap). But it might be simpler at first to exclude them like we do in TranscriptClean. It mostly matters from a data structure-ID point of view.
