### ISSUE TITLE
Build TALON annotation database

### ISSUE THREAD

**Issue by dewyman** [mortazavilab/TALON#30]
In order to track novel transcripts from run to run, it is crucial to maintain an external structure to store and update the annotations.

### TODO
- [x] Take existing GTF parsing function from main TALON script and adapt it for creating a new annotation tracker instead (outside of main TALON script). Add filtering to remove irrelevant annotations.
- [x] Add dataset-tracking table to database and update TALON input options accordingly
- [ ] Write a function to output the entire annotation tracker in GTF format for viewing in the UCSC genome browser, etc.
- [x] Update main TALON script to parse the annotation instead of a GTF file
- [x] Clean up transcript identification code 
- [x] Write code in main TALON script to appropriately modify the annotation.

### Requirements
* Allow single runs of talon that combine multiple (1) technical and (2) biological replicates in a single run.
* Track gene, transcript, and exon locations
* Track how many datasets the transcript has been found in to date, and probably which ones (see point about 'bad' information). **We need to identify when/where we first identify a new transcript, but we probably need to identify in a separate file when we observe existing transcripts and the abundance. This is just as interesting for "real" biology as finding new ones.**
    * This could also be helpful as a way of generating cell-line specific annotations (i.e. filter the annotation to include only transcripts from GM12878 datasets). **Yes, for both known and novel transcripts.**
* Track whether an entry originated in an annotation like GENCODE or if it came from a long read dataset(s). **We need to assign novel transcript IDs using a counter. It's ok if we decide to "reject" transcripts later, for example because they have non-canonical junctions.**
* In terms of our lab, the database/annotation needs to be set up in such a way that Gaby and I can both access it and write to it. Otherwise, we won't be able to compare our datasets. This does create a potential problem though- it means that we can't both run things on it at once. Also, how would this scale if we want to share our annotations with other people? **More importantly, this pipeline needs to ultimately be run by the ENCODE DCC based on our raw data. So it's important that it works in a standard environment such as AWS.**
* Need to protect against addition of 'bad' information, i.e. if we decide that a dataset we ran can't be trusted, then there needs to be a mechanism for removing things that were discovered during that run. **Yes, but that could be accomplished by keeping track of previous runs before running additional one (e.g. versioning and storing the previous runs).** 
    * Check for collisions when adding information, including situations where a dataset is accidentally run in duplicate. **If you rerun the same sample and add new information, then it's a bug. The only way I could see this as a potential problem is if you did abundance filtering, reran the same sample and now a solo transcript was "double-counted", so watch out for that.** 
    * May want to apply filtering (abundance > 1) before adding a novel transcript to annotation. **Not optional, but necessary for new transcripts. But more importantly, only accept novel transcripts seen in biological replicates.**
* The format should be convenient with respect to the TALON code, i.e. quick to read in. **Not only quick, but also filtered from irrelevant Gencode stuff that we should not see.**
* Be able to output a GTF version
* Be able to get a list of every dataset that is represented in the annotation. **Ultimately, we want to also track abundances in a separate file that will match what's in this annotation file.**

### Anticipated challenges
* 5' and 3' differences: How large should the difference be in order to create a new transcript entry? What if this creates problems with retroactively sub-optimal transcript matches?

**Example:** Candidate 1 is assigned to the known transcript A.1 because its 5' difference is within some pre-determined threshold. However, when TALON encounters Candidate 2, a new transcript is created. If we see another transcript with the same structure as Candidate 1 (labeled 3 here), will the behavior be the same as for Candidate 1, or will it be assigned to Candidate 2? The concern here is to avoid different outcomes when the order of the input changes. We need TALON to behave deterministically.

![5 transcript assignment issue](https://user-images.githubusercontent.com/8904542/39443760-6c060952-4c6a-11e8-9427-d511806e5e61.jpg)

* Should we ever allow people to merge annotations?
    * If we do this, there needs to be a clean mechanism for remapping IDs in datasets that were processed in the past. **I am not sure that it's necessary. We can assume that the annotation is run serially.**
* If we upgrade to a new version of GENCODE, what happens? **Also, how do we migrate to a new version of the genome assembly ?**

### Tests
* If we run the same dataset twice, then the second run should not make any changes to the database at all. **Yes.**
* TALON should produce the same results regardless of the order of the input file, **except that the assigned new IDs would be different.**

### Ideas
* Transcript and associated information should occupy a single line in order to make parsing as simple as possible. **We might want to consider the way UCSC records transcripts in their tables.**
    * UCSC GENCODE v24 schema: https://genome.ucsc.edu/cgi-bin/hgTables
* Right now, when a novel transcript is found, it is immediately added to the data structures of the current run. If I want to screen transcripts (i.e. for min abundance) before adding them to the database, this could be done in a separate iteration over novel transcripts at the end of the run. **It's ok to add them to the structure, but we want to filter what's added at the end of the run based on being seen at least once in each of two biological replicates.**
* When outputting to GTF, include number of datasets each transcript is found in- maybe we could color based on this in the genome browser.
