### ISSUE TITLE
Develop the Transcript class

### ISSUE THREAD

**Issue by dewyman** [mortazavilab/TALON#5]
## High Level
The Transcript class needs to
* Allow fast comparison of transcripts on the level of "are they identical or not"
* Be flexible- some users may care about differences at the 5' end and others may not (for example)
* Be able to handle data from the GTF annotation or from the SAM file so that transcripts from these two sources can be readily compared

See #1 for additional considerations.

### Thoughts
* Develop SamTranscript as a subclass of Transcript, with additional attributes for storing SAM information
* I think it will be more appropriate to define transcripts in terms of their exons (instead of their introns) because GENCODE is based around exons. The SAM files are more intron-oriented, but it shouldn't be hard to convert over. Could use the CIGAR string 
* Initialization should not require gene information as a mandatory field, because we won't have this information right away for the SAM transcripts
* Start and end relative to assigned gene: At first, I thought I should make it a requirement that the transcript be situated entirely within the gene start and end. But I actually think that assumption may be violated with novel transcripts on occasion.
* Start, end, and strand should probably be mandatory initialization fields
* It would be really cool if I had a way of computing the 5' UTR and/or 3' UTR length of a transcript object

## Tasks
- [x] Write basic class structure
- [x] Write subclass for SAM transcripts
- [x] Write code to create transcript object from GTF entry
- [x] Implement string representation function (really simple for now)
